'use strict';
let session=null,queue=null,current=null;
const $=s=>document.querySelector(s);
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;}
function notify(text,error=false){$('#notice').textContent=text;$('#notice').className=error?'error':'';}
async function api(path,data){const headers={};if(data!==undefined){headers['Content-Type']='application/json';headers['X-CSRF-Token']=session?.csrf||'';}const r=await fetch(path,{method:data===undefined?'GET':'POST',headers,body:data===undefined?undefined:JSON.stringify(data),credentials:'same-origin'});const result=await r.json();if(!r.ok){if(r.status===401){session=null;showSession();}throw new Error(result.error||'Request blocked');}return result;}
function showSession(){const ok=!!session;$('#login').hidden=ok;$('#workspace').hidden=!ok;$('#identity').textContent=ok?`${session.username} / ${session.role}`:'';}
function field(form,label,name,type='text',value='',required=true){const l=node('label',label);const i=document.createElement('input');i.name=name;i.type=type;i.value=value;i.required=required;if(type==='number'){i.step='any';i.min='0';}l.append(i);form.append(l);return i;}
function actionButton(text,fn,cls='secondary'){const b=node('button',text,cls);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){notify(e.message,true);}finally{b.disabled=false;}};return b;}
function formSubmit(form,handler){form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button[type=submit]')||form.querySelector('button');if(b)b.disabled=true;try{await handler(new FormData(form));}catch(err){notify(err.message,true);}finally{if(b)b.disabled=false;}};}
async function refresh(){queue=await api('/api/queue');$('#mode').textContent=queue.mode==='DEMO'?'DEMO • Synthetic records • Remote execution locked':'Private station • Internal warehouse actions only';const metrics=$('#metrics');metrics.replaceChildren();for(const [label,value] of [['Open work orders',queue.work.filter(x=>!['CANCELLED','CLOSED'].includes(x.state)).length],['Cartons captured',queue.work.reduce((n,x)=>n+x.captured,0)],['Sealed packouts',queue.work.filter(x=>x.state==='PACKED').length],['Exceptions',queue.exceptions.length+queue.resources.filter(x=>x.available<0||x.expired).length]]){const m=node('div',undefined,'metric');m.append(node('span',label),node('strong',value));metrics.append(m);}const tb=$('#queue');tb.replaceChildren();for(const w of queue.work){const tr=node('tr'),a=node('td');a.append(node('strong',w.work_key),node('small',w.msku));const st=node('td');st.append(node('span',w.state.replaceAll('_',' '),'badge'+(w.overdue?' warning':'')));const qty=node('td',`${w.captured} / ${w.cartons}`);qty.append(node('small',`${w.units} sellable units`));const due=node('td',w.owner||'Unassigned');due.append(node('small',w.deadline?new Date(w.deadline).toLocaleString():'Not released'));const btn=node('td');btn.append(actionButton('Open',()=>load(w.work_key)));tr.append(a,st,qty,due,btn);tb.append(tr);}if(!queue.work.length){const tr=node('tr'),td=node('td','No work orders imported.','empty');td.colSpan=5;tr.append(td);tb.append(tr);}renderResources();if(current)await load(current);}
function renderResources(){const r=$('#resources');r.replaceChildren(node('h2','Shared resources'));if(session.role!=='supervisor'){r.append(node('p','Resource allocation and release are managed by supervisors.'));return;}if(!queue.resources.length)r.append(node('p','Import reconciled counts and measured recipes before releasing work.'));for(const item of queue.resources){const row=node('div',undefined,'resource');row.append(node('strong',item.resource_id),node('small',`${item.kind} / ${item.unit} / revision ${item.revision}`),node('div',`${item.kind==='cash'?'$'+(item.available/100).toFixed(2):item.available} available · ${item.kind==='cash'?'$'+(item.held/100).toFixed(2):item.held} reserved`,'totals'));if(item.available<0||item.expired)row.append(node('span',item.available<0?'SHORT COUNT — BLOCKED':'EVIDENCE EXPIRED','badge warning'));else row.append(node('small',`Evidence valid until ${new Date(item.valid_until).toLocaleString()}`));r.append(row);}}
async function workAction(name,data){await api(`/api/work/${encodeURIComponent(current)}/${name}`,data);notify('Saved. No remote shipment, label purchase or receipt claim was made.');await refresh();}
async function load(key){current=key;const d=await api(`/api/work/${encodeURIComponent(key)}`),root=$('#detail'),p=d.plan,s=p.pack_spec;root.replaceChildren(node('h2',key),node('p',`${p.msku} · ${p.planned_units} units · ${p.cartons} cartons`));const spec=node('div',undefined,'spec');for(const [label,value] of [['Sellable unit',`${s.unit_dimensions_in.join(' × ')} in / ${s.unit_gross_lb} lb gross`],['Approved carton',`${s.carton_dimensions_in.join(' × ')} in / ${s.carton_gross_lb} lb gross`],['Scan this FNSKU',s.fnsku],['Pack revision / units per carton',`${s.version} / ${s.units_per_carton}`]]){const b=node('div');b.append(node('strong',label),node('span',value));spec.append(b);}root.append(spec);
if(d.state==='DRAFT'&&session.role==='supervisor'){root.append(node('h3','Release to warehouse'));const f=node('form'),grid=node('div',undefined,'fields');const l=node('label','Measured resource recipe'),sel=document.createElement('select');sel.name='recipe_id';sel.required=true;for(const r of queue.recipes.filter(r=>r.msku===p.msku&&r.pack_version===s.version)){const o=node('option',r.recipe_id);o.value=r.recipe_id;sel.append(o);}l.append(sel);grid.append(l);field(grid,'Named owner','owner','text',session.username);field(grid,'Promised completion (local time)','deadline','datetime-local');field(grid,'Release review evidence','evidence_ref');f.append(grid);const b=node('button','Reserve resources & release');b.type='submit';f.append(b);formSubmit(f,async fd=>workAction('release',{recipe_id:fd.get('recipe_id'),owner:fd.get('owner'),deadline:new Date(fd.get('deadline')).toISOString(),evidence_ref:fd.get('evidence_ref'),plan_digest:d.plan_digest}));root.append(f);}
if(['RELEASED','PACKING'].includes(d.state)&&session.role!=='viewer'){root.append(node('h3','Capture an actual carton'));const f=node('form'),g=node('div',undefined,'fields');field(g,'Scan local box barcode','local_box_id');field(g,'Scan FNSKU','fnsku');field(g,'Lot / handling-unit reference','lot_ref');field(g,'Units inside carton','units','number',s.units_per_carton);field(g,'Actual gross weight (lb)','gross_lb','number');field(g,'Actual length (in)','length','number');field(g,'Actual width (in)','width','number');field(g,'Actual height (in)','height','number');field(g,'Measurement / scale evidence','measurement_evidence_ref');f.append(g);f.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.tagName==='INPUT'){const ins=[...f.querySelectorAll('input')],next=ins[ins.indexOf(e.target)+1];if(next){e.preventDefault();next.focus();next.select();}}});const b=node('button','Record carton');b.type='submit';f.append(b);formSubmit(f,async fd=>{const data=Object.fromEntries(fd);for(const k of ['units','gross_lb'])data[k]=Number(data[k]);data.dimensions_in=['length','width','height'].map(k=>Number(data[k]));for(const k of ['length','width','height'])delete data[k];data.msku=p.msku;data.pack_version=s.version;await workAction('scan',data);});root.append(f);}
root.append(node('h3',`Captured cartons (${d.boxes.length} / ${p.cartons})`));for(const box of d.boxes){const row=node('div',undefined,'resource');row.append(node('strong',box.local_box_id),node('small',`${box.units} units / ${box.gross_lb} lb / ${box.dimensions_in.join(' × ')} in`),node('small',`${box.lot_ref} / ${box.packed_by}`));const labels=d.box_links?.[box.local_box_id];if(labels)row.append(node('small',`${labels.amazon_box_id} / ${labels.carrier} / ${labels.tracking_number}`));if(session.role==='supervisor'&&['PACKING','PACKED'].includes(d.state))row.append(actionButton('Void & recapture',async()=>{const ev=prompt('Correction reason and evidence. The original scan will be retained.');if(ev)await workAction('void',{box_id:box.local_box_id,evidence_ref:ev});},'danger'));root.append(row);}
if(session.role==='supervisor'){const controls=node('div',undefined,'inline');if(['RELEASED','PACKING'].includes(d.state))controls.append(actionButton('Review & seal packout',async()=>{const ev=prompt('Packout review evidence reference:');if(ev)await workAction('seal',{evidence_ref:ev});}));if(['DRAFT','RELEASED'].includes(d.state))controls.append(actionButton('Cancel untouched work',async()=>{const ev=prompt('Cancellation evidence reference:');if(ev)await workAction('cancel',{evidence_ref:ev});},'danger'));root.append(controls);}
if(d.state==='PACKED'&&session.role!=='viewer'){const details=node('details');details.append(node('summary','Link an Amazon box ID and individual carrier tracking'));const f=node('form'),g=node('div',undefined,'fields');for(const [label,name] of [['Local carton barcode','box_id'],['Amazon box ID','amazon_box_id'],['Carrier','carrier'],['Individual tracking number','tracking_number'],['Label scan evidence','evidence_ref']])field(g,label,name);f.append(g);const b=node('button','Save label linkage');b.type='submit';f.append(b);formSubmit(f,fd=>workAction('link',Object.fromEntries(fd)));details.append(f);root.append(details);}
if(d.state==='PACKED'&&session.role==='supervisor'){const details=node('details');details.append(node('summary','Prepare Amazon packing proposal — no submission'));const f=node('form');for(const [label,name] of [['Unique action key','action_key'],['Account scope: amazon:NA:seller:marketplace','scope'],['Current API inbound plan ID','inbound_plan_id'],['Confirmed packing group ID','packing_group_id'],['Assignment / prep evidence','evidence_ref']])field(f,label,name);for(const name of ['prep_owner','label_owner']){const l=node('label',name.replace('_',' ')),sel=document.createElement('select');sel.name=name;for(const value of ['SELLER','NONE']){const o=node('option',value);o.value=value;sel.append(o);}l.append(sel);f.append(l);}field(f,'Proposal expiry (local time)','valid_until','datetime-local');const b=node('button','Stage exact packing proposal');b.type='submit';f.append(b);formSubmit(f,fd=>{const x=Object.fromEntries(fd);x.valid_until=new Date(x.valid_until).toISOString();return workAction('prepare-packing',x);});details.append(f);root.append(details);}
if(d.events){const details=node('details');details.append(node('summary','Audit trail'));for(const e of d.events){const row=node('div',`${e.kind} · ${e.actor}`,'event');row.append(node('small',new Date(e.recorded_at).toLocaleString()));details.append(row);}root.append(details);}}
$('#login-form').onsubmit=async e=>{e.preventDefault();try{session=await api('/api/login',Object.fromEntries(new FormData(e.target)));e.target.reset();showSession();notify('');await refresh();}catch(err){notify(err.message,true);}};
$('#refresh').onclick=()=>refresh().catch(e=>notify(e.message,true));$('#logout').onclick=async()=>{try{await api('/api/logout',{});session=null;current=null;showSession();}catch(e){notify(e.message,true);}};
(async()=>{try{session=await api('/api/session');showSession();await refresh();}catch{showSession();}})();
